### ISSUE TITLE
A new crash with the build : BungeeCord-v95-custom.

### ISSUE THREAD

**Issue by ccxufo** [densitycraft/ForgePacketFix#6]
Sorry,I couldn't found the issues page in BungeeCord. 
When I turn to use this version of bungeecord :https://github.com/densitycraft/BungeeCord. 
Client will crash when players join the game.This is very embarrassing that it would not crash when I use the https://github.com/HexagonMC/BungeeCord/releases.   
http://pastebin.com/ewSbEfzK

**Comment by thomas15v** [comment]
You cannot use BungeeTabList or any team based bungeecord plugin.
